### ISSUE TITLE
cancel alarm

### ISSUE THREAD

**Issue by edwinmacalopu** [mevljas/flutter_alarm_clock#1]
Could you see an option to cancel an alarm already created?

**Comment by mevljas** [comment]
Thanks for the suggestion! I'm definitely planning to do that in the future, but currently, I'm pretty swamped with my other projects. Feel free to open a pull request. 😄

**Comment by thomassth** [comment]
It's not trivial, all intents in the common intent list are already implemented:

https://developer.android.com/guide/components/intents-common

Which means no guarantee all alarm apps can accept a cancel command.

**Comment by mevljas** [comment]
Not much we can do about those apps. 🙂

**Comment by thomassth** [comment]
I stand corrected, there's more intents for alarms, including searching and dismissing alarms
https://developer.android.com/reference/android/provider/AlarmClock#ACTION_DISMISS_ALARM

**Comment by mevljas** [comment]
Yeah I thought so. I'm not sure why they aren't listed under common intents. If i remember correctly there's no wrapper class for those and they have to be hardcoded.
