### ISSUE TITLE
Fix request for kotlin version

### ISSUE THREAD

**Issue by ghost** [mevljas/flutter_alarm_clock#11]
With the latest version of flutter, it's impossible to build a project with flutter_alarm_clock. here the stack :

FAILURE: Build failed with an exception.

What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_alarm_clock' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

 Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

 Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1

Can you update the kotlin_version to `build.gradle` in the `android/build.gradle` file ?

Thank you

**Comment by mevljas** [comment]
I'll look at it in the next few days.
